"""user daily_goal

Revision ID: 5c06b876043d
Revises: b4461f00ed31
Create Date: 2026-06-12 09:15:29.679230

"""
from alembic import op
import sqlalchemy as sa


revision = '5c06b876043d'
down_revision = 'b4461f00ed31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_goal', sa.Integer(), nullable=False, server_default='3'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('daily_goal')

    # ### end Alembic commands ###
