"""nudge windows

Revision ID: 7412e427de21
Revises: 8f5f4fbf6766
Create Date: 2026-06-12 18:45:02.853020

"""
from alembic import op
import sqlalchemy as sa


revision = '7412e427de21'
down_revision = '8f5f4fbf6766'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nudge_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_hour', sa.Integer(), nullable=False),
    sa.Column('end_hour', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_nudge_windows_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nudge_windows'))
    )
    with op.batch_alter_table('nudge_windows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_nudge_windows_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nudge_windows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_nudge_windows_user_id'))

    op.drop_table('nudge_windows')
    # ### end Alembic commands ###
