"""attempt conversation messages

Revision ID: 8f5f4fbf6766
Revises: 5c06b876043d
Create Date: 2026-06-12 15:46:01.728417

"""
from alembic import op
import sqlalchemy as sa


revision = '8f5f4fbf6766'
down_revision = '5c06b876043d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attempt_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('modality', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], name=op.f('fk_attempt_messages_attempt_id_attempts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempt_messages'))
    )
    with op.batch_alter_table('attempt_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempt_messages_attempt_id'), ['attempt_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempt_messages_attempt_id'))

    op.drop_table('attempt_messages')
    # ### end Alembic commands ###
