"""enrollment policy toggles + notification outbox

Revision ID: a405b2d183ea
Revises: dd311a18576d
Create Date: 2026-06-11 16:20:34.481574

"""
from alembic import op
import sqlalchemy as sa


revision = 'a405b2d183ea'
down_revision = 'dd311a18576d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default on every NOT NULL column so existing rows upgrade in place
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selection_strategy', sa.String(length=40),
                                      nullable=False, server_default='due_then_weakest'))
        batch_op.add_column(sa.Column('repeat_cooldown_hours', sa.Float(),
                                      nullable=False, server_default='6.0'))
        batch_op.add_column(sa.Column('marking_strictness', sa.String(length=20),
                                      nullable=False, server_default='balanced'))
        batch_op.add_column(sa.Column('question_style', sa.String(length=20),
                                      nullable=False, server_default='plain'))

    with op.batch_alter_table('notification_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_ref', sa.String(length=300),
                                      nullable=False, server_default=''))
        batch_op.add_column(sa.Column('attempts', sa.Integer(),
                                      nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_notification_log_status'), ['status'], unique=False)
    # rows written before the outbox existed were delivered immediately
    op.execute("UPDATE notification_log SET delivered_at = sent_at WHERE status = 'sent'")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_log_status'))
        batch_op.drop_column('delivered_at')
        batch_op.drop_column('attempts')
        batch_op.drop_column('channel_ref')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_column('question_style')
        batch_op.drop_column('marking_strictness')
        batch_op.drop_column('repeat_cooldown_hours')
        batch_op.drop_column('selection_strategy')

    # ### end Alembic commands ###
