"""question bank + question_source policy

Revision ID: b4461f00ed31
Revises: a405b2d183ea
Create Date: 2026-06-11 23:11:22.387446

"""
from alembic import op
import sqlalchemy as sa


revision = 'b4461f00ed31'
down_revision = 'a405b2d183ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('commentary', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_questions_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_skill_id'), ['skill_id'], unique=False)

    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_attempts_question_id_questions'), 'questions', ['question_id'], ['id'], ondelete='SET NULL')

    # server_default so existing enrollment rows upgrade in place
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_source', sa.String(length=20),
                                      nullable=False, server_default='bank_first'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_column('question_source')

    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_attempts_question_id_questions'), type_='foreignkey')
        batch_op.drop_column('question_id')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_skill_id'))

    op.drop_table('questions')
    # ### end Alembic commands ###
