"""initial schema

Revision ID: dd311a18576d
Revises: 
Create Date: 2026-06-11 12:11:47.402725

"""
from alembic import op
import sqlalchemy as sa


revision = 'dd311a18576d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=60), nullable=False),
    sa.Column('quiet_hours_start', sa.Integer(), nullable=False),
    sa.Column('quiet_hours_end', sa.Integer(), nullable=False),
    sa.Column('max_prompts_per_day', sa.Integer(), nullable=False),
    sa.Column('profile_note', sa.Text(), nullable=False),
    sa.Column('next_decision_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('channel_ref', sa.String(length=300), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_devices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices')),
    sa.UniqueConstraint('user_id', 'channel', 'channel_ref', name=op.f('uq_devices_user_id'))
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_user_id'), ['user_id'], unique=False)

    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=80), nullable=False),
    sa.Column('level', sa.String(length=80), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_programs_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programs'))
    )
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_programs_owner_id'), ['owner_id'], unique=False)

    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('exam_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_enrollments_program_id_programs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_enrollments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollments')),
    sa.UniqueConstraint('user_id', 'program_id', name=op.f('uq_enrollments_user_id'))
    )
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollments_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enrollments_user_id'), ['user_id'], unique=False)

    op.create_table('notification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_notification_log_device_id_devices'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_log_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_log'))
    )
    with op.batch_alter_table('notification_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_log_sent_at'), ['sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_log_user_id'), ['user_id'], unique=False)

    op.create_table('units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['units.id'], name=op.f('fk_units_parent_id_units'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_units_program_id_programs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_units'))
    )
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_units_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_units_program_id'), ['program_id'], unique=False)

    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=40), nullable=False),
    sa.Column('effort', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_skills_program_id_programs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('fk_skills_unit_id_units'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills'))
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_program_id'), ['program_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_unit_id'), ['unit_id'], unique=False)

    op.create_table('attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('asked_at', sa.DateTime(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_attempts_enrollment_id_enrollments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_attempts_skill_id_skills'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_attempts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempts'))
    )
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempts_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_attempts_user_open', ['user_id', 'verdict'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_notes_skill_id_skills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name=op.f('fk_notes_unit_id_units'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_unit_id'), ['unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_user_id'), ['user_id'], unique=False)

    op.create_table('skill_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('interval_hours', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], name=op.f('fk_skill_states_enrollment_id_enrollments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_skill_states_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_states')),
    sa.UniqueConstraint('enrollment_id', 'skill_id', name=op.f('uq_skill_states_enrollment_id'))
    )
    with op.batch_alter_table('skill_states', schema=None) as batch_op:
        batch_op.create_index('ix_skill_states_due_at', ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_states_enrollment_id'), ['enrollment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_states_skill_id'), ['skill_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_states_skill_id'))
        batch_op.drop_index(batch_op.f('ix_skill_states_enrollment_id'))
        batch_op.drop_index('ix_skill_states_due_at')

    op.drop_table('skill_states')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_user_id'))
        batch_op.drop_index(batch_op.f('ix_notes_unit_id'))
        batch_op.drop_index(batch_op.f('ix_notes_skill_id'))

    op.drop_table('notes')
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_attempts_user_open')
        batch_op.drop_index(batch_op.f('ix_attempts_user_id'))

    op.drop_table('attempts')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_unit_id'))
        batch_op.drop_index(batch_op.f('ix_skills_program_id'))

    op.drop_table('skills')
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_units_program_id'))
        batch_op.drop_index(batch_op.f('ix_units_parent_id'))

    op.drop_table('units')
    with op.batch_alter_table('notification_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_log_sent_at'))

    op.drop_table('notification_log')
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollments_user_id'))
        batch_op.drop_index(batch_op.f('ix_enrollments_program_id'))

    op.drop_table('enrollments')
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_programs_owner_id'))

    op.drop_table('programs')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_user_id'))

    op.drop_table('devices')
    op.drop_table('users')
    # ### end Alembic commands ###
